#!/bin/bash

set -e


PUID=${PUID:-500}
PGID=${PGID:-500}
ENV=${APP_ENV:-production}


groupmod -o -g "$PGID" www-data
usermod -o -u "$PUID" www-data


if [ "$ENV" != "production" ]; then
    echo "Enabling xdebug in development"

    ## FPM
    ln -sf /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini

    ## CLI
    ln -sf /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/cli/conf.d/20-xdebug.ini
else
    echo "Disabling xdebug in production"

    ## FPM
    if [ -e /etc/php/7.4/fpm/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.4/fpm/conf.d/20-xdebug.ini
    fi

    ## CLI
    if [ -e /etc/php/7.4/cli/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.4/cli/conf.d/20-xdebug.ini
    fi
fi


exec "$@"